version: '3.9'

networks:
  nginx_net:
    driver: bridge

services: 
  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - nginx_net

