services: 

  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - nginx_net

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
  

networks:
  nginx_net:
    driver: bridge

volumes:
  mongo-data: